### ISSUE TITLE
轨迹ID不稳定

### ISSUE THREAD

**Issue by arvinxian** [Qidian213/deep_sort_yolov3#1]
你好，我跑了你的项目之后，用本地的视频，发现视频中行人轨迹的ID经常变化，这个问题再deep sort项目中也报过issue ，我尝试把你demo中可视化的那个循环修改后问题同样存在。
环境Ubuntu16.04，python2.7
issue 参照
https://github.com/nwojke/deep_sort/issues/13
里面貌似@bendidi用的可视化的代码和你类似 是用一个循环写的

update：
在循环内跟踪框之前 加一条判断语句就可以了，
`if track.is_confirmed() and track.time_since_update <=0:`

**Comment by Qidian213** [comment]
显示部分我是参考的上面指出的那个人的程序，检测是不是测试加了这句后效果依然不好？ 我也纠结过这个问题，以为是检测帧率过低，或匹配跟踪部分的问题，毕竟相对于官方测试数据集中每一帧都做好了标注，这里很容易出现相邻检测帧间图像中人移动距离较大，位置预测追踪失败的问题。 我这工程我当时只是移植下做了下测试，不符合我们要做的项目需求，就没有再深入研究，转手忙别的去了，一直也没时间深入。有时间我会详细看下。你要是有解决办法，烦请指点一二 ！

**Comment by Qidian213** [comment]
这个问题，我目前也没有很好的解决。按我猜测你加了这句后效果不会变好。

**Comment by ZhihongChen123** [comment]
哈喽，我也碰到了这个问题，请问你解决了这个问题吗？ @arvinxian

**Comment by arvinxian** [comment]
嗯，之前是ID直接不稳定，一直在边，在添加了之前的那句之后 ID稳定下来了 ，虽然不是一直很稳定，当遮挡时间比较长的时候，还是会分配新的ID，我看了tracker.py里的代码后，感觉应该是max_age参数来影响的，当我尝试把max_age试着调大一些后，ID稳定情况会好一些

**Comment by arvinxian** [comment]
@Qidian213 我也是看到开始Issue里那个问题里作者解释的ID不稳定的原因才想起添加这句来判断的，作者的意思是我们当前帧中检测到的结果和追踪的很有可能不是同一物体，两者不是必须同时联系起来的。所以我看你可视化追踪里在一个循环里把检测的和追踪的结果同时渲染出来，是导致结果ID里极不稳定的原因，在添加了对是否新建追踪的判断后，ID的情况的确有明显的改善。还是十分感谢你做的工作，so  cool 。
我在你项目的基础上增加了行人轨迹的绘制，目前效果挺不错的，

之前提到Deep SORT的issue里作者的原话@nwojke
> but the number of detections and tracks will usually not be the same. Also, the i-th detection at time k is by no means associated with the i-th track at time k.

**Comment by ZhihongChen123** [comment]
嗯嗯，很高兴看到你已经解决问题，请问你是在哪里添加if track.is_confirmed() and track.time_since_update <=0:这条判断语句呢？谢谢 @arvinxian

**Comment by Qidian213** [comment]
@arvinxian 期待你的工作测试效果

**Comment by Qidian213** [comment]
有时间我会采用官方源码的显示方式修改下代码

**Comment by Qidian213** [comment]
问题解决了，现在测试比较稳定，只需要把追踪检测分开

**Comment by 7LFB** [comment]
the unstable track id was caused by placement error in visualization. the track id should be put on the box calculated by 'track.to_tlbr()',  not 'det.to_tlbr()'.

**Comment by Innerpeace90** [comment]
@Qidian213 你好！要实现“问题解决了，现在测试比较稳定，只需要把追踪检测分开”怎么修改代码呢？作者可否更新一下

**Comment by irisqp** [comment]
> 循环内跟踪框之前
你好，请问具体是在代码的哪个地方加这句呢？

**Comment by Qidian213** [comment]
@irisqp 已经改正过了

**Comment by irisqp** [comment]
> 
> 
> @irisqp 已经改正过了
好的，谢谢啦

**Comment by yoming723** [comment]
@Qidian213 How do I draw a route for pedestrians to walk?
I need to analyze their direction

**Comment by yoming723** [comment]
@arvinxian How do I draw a route for pedestrians to walk?
I need to analyze their direction
