### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by qiyayun** [Qidian213/deep_sort_yolov3#10]
![screenshot from 2018-06-03 23-21-18](https://user-images.githubusercontent.com/26948544/40888144-4b9d7656-6785-11e8-90b3-40e8c1f8010d.png)
hello,when I test my video ,it doesn't work. I have replaced VideoCapture(0) with  VideoCapture(to/my/path) ,Need i prepare any other files? thanks

**Comment by Qidian213** [comment]
have you solved  it ? it seems that it can't  use your camera  , have  you tested use a video file by   "video_capture = cv2.VideoCapture("path  to video ") ?

**Comment by qiyayun** [comment]
好像是是没法读进去我的视频，你们有安装ffmpeg吗

**Comment by Qidian213** [comment]
应该是需要安装的

**Comment by aimhabo** [comment]
搜ubuntu+anaconda+tensorflow的教程，按顺序配完应该是可以的

我的倒是可以读视屏，但是把参数模型从
```
    #model_filename = 'model_data/mars-small128.pb'
    model_filename = 'model_data/yolo.h5'
```
就出现
```
model_data/yolo.h5 model, anchors, and classes loaded.
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    main(YOLO())
  File "demo.py", line 33, in main
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "/home/aimhabo/nonmine-craft/deep_sort_yolov3/tools/generate_detections.py", line 100, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/home/aimhabo/nonmine-craft/deep_sort_yolov3/tools/generate_detections.py", line 81, in __init__
    "net/%s:0" % input_name)
  File "/home/aimhabo/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3766, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/aimhabo/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/aimhabo/anaconda2/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3632, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."
```
不改的话用mars-small128.pb输出就无效果，也没看到哪里有写需要预选框的地方

**Comment by Qidian213** [comment]
两个模型都要用，yolo.h5是yolo检测用的，mars-small128.pb是追踪用的。 yolo.h5需要你自己转换，并放到 model_data 文件夹下 。 上面 model_filename 是追踪用的模型名字

**Comment by aimhabo** [comment]
@Qidian213 成了！非常感谢，我自己转化的.h5小了20多MB，估计是转化出了问题

**Comment by qiyayun** [comment]
我把opencvd的版本改了，现在是cuda9.0+opencv3.3,装好之后就可以读入视频了，但是会有两个重叠的白框和蓝框/home/dip_image/Pictures/Screenshot from 2018-06-12 20-12-43.png

**Comment by boyob** [comment]
> 两个模型都要用，yolo.h5是yolo检测用的，mars-small128.pb是追踪用的。 yolo.h5需要你自己转换，并放到 model_data 文件夹下 。 上面 model_filename 是追踪用的模型名字

两个模型都是model_filename，运行的时候需要一个就可以吧？ 我也是出现错误：“KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."
请问该怎么办？
