### ISSUE TITLE
How to make full use of GPU?

### ISSUE THREAD

**Issue by EYHN** [Qidian213/deep_sort_yolov3#11]
Thanks for your work, the tracking is amazing, but I need your help to improve the speed.

I use a gtx1080ti to run this demo.
The gpu usage rate only 15%-20%, and the memory occupancy rate is only 7%.

How to make full use of GPU?

**Comment by Qidian213** [comment]
how  about the speed ? performs well ?

**Comment by EYHN** [comment]
I maked the CPU do less work and increase GPU usage to 60%.
Can yolo batch detect pictures? That should be much faster.

**Comment by EYHN** [comment]
@aimhabo
要先装好 cuda 和 cudnn
再根据cuda版本下载 tensorflow-GPU 或者自行编译

**Comment by Qidian213** [comment]
都是中国人，跟我飚啥英语？<(￣3￣)>哼！

**Comment by EYHN** [comment]
我现在急需提升运行速度啊
能否并行调用 tf.session.run 太提高利用率？

**Comment by EYHN** [comment]
能不能改写成使用 tensorflow 队列传输数据啊，大佬帮帮我啊。

**Comment by aimhabo** [comment]
@EYHN 不行啊，就是这与装的，fps不到0.3，直接在darknet里做都有2的

**Comment by Qidian213** [comment]
终端使用 nvidia-smi 查看GPU 使用情况 @aimhabo

**Comment by Qidian213** [comment]
并行？ yolo 的session 和deep_sort的session并行运行？ 那样的话需要解决检测框与图像的匹配，保证正确的传输给deep_sort 。 实际上如果你做过测试，deep_sort 基本不影响速度，单纯的运行deep_sort速度非常快，主要限制来自于yolo 。可以尝试在yolo部分加速，或去掉视频存储，检测框存储等功能。
还有我主要学习的不是tensorflow,对于tensorflow更多的东西不很了解。

**Comment by EYHN** [comment]
目前我是增加了视频读取缓存，增加了一个线程专门绘制检测框和输出视频
yolo和deep_sort共用同一个session
现在可以达到27fps，yolov3官网titan x 能跑 35fps，感觉还可以优化。

**Comment by Qidian213** [comment]
做的不错！

**Comment by EYHN** [comment]
I closed this issue.
About the batch detect pictures: https://github.com/qqwweee/keras-yolo3/issues/15

**Comment by Innerpeace90** [comment]
@EYHN 

你好！可以看看你的代码吗？三扣~~~

**Comment by EYHN** [comment]
@Innerpeace90 
相关的代码在我fork的repository中 https://github.com/EYHN/deep_sort_yolov3/tree/eyhn

**Comment by yihsuanhsu** [comment]
我還是無法使用GPU跑耶~請問該如何使用呢?
目前command是直接下 python demo.py

**Comment by yihsuanhsu** [comment]
@EYHN 
你好~請問你有成翁加速嗎?我也很需要能提高速度~感謝

**Comment by ntucschen** [comment]
> 目前我是增加了视频读取缓存，增加了一个线程专门绘制检测框和输出视频
> yolo和deep_sort共用同一个session
> 现在可以达到27fps，yolov3官网titan x 能跑 35fps，感觉还可以优化。
@EYHN 想請問具體要怎麼實現？

**Comment by gogoIsComing** [comment]
> I maked the CPU do less work and increase GPU usage to 60%, 20 fps
> Can yolo batch detect pictures? That should be much faster.

can you explain how did you increased the performance to 20fps ????

**Comment by MuhammadAsadJaved** [comment]
> @Innerpeace90
> 相关的代码在我fork的repository中 https://github.com/EYHN/deep_sort_yolov3/tree/eyhn

This code is running at 27 FPS?

**Comment by MuhammadAsadJaved** [comment]
@gogoIsComing 
use this repo
https://github.com/MuhammadAsadJaved/deep_sort_yolov3

Eyhn made some changed and I also changed a little from her repo.
