### ISSUE TITLE
Unable to use yolov3-tiny.h5 and my own Keras model .h5

### ISSUE THREAD

**Issue by cvtak** [Qidian213/deep_sort_yolov3#119]
Hi.
I tried to use yolov3-tiny.h5 by changing these 3 line in yolo.py

    self.model_path = 'model_data/yolov3-tiny.h5 '
    self.anchors_path = 'model_data/tiny_yolo_anchors.txt'
    self.classes_path = 'model_data/coco_classes.txt'

It works well on Keras-Yolo3 but error happened on deep sort yolov3 below.

  File "demo_car.py", line 112, in <module>
    main(YOLO())
  File "C:\YOLOv3\deep_sort_yolov3-master\yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "C:\YOLOv3\deep_sort_yolov3-master\yolo.py", line 72, in generate
    score_threshold=self.score, iou_threshold=self.iou)
  File "C:\YOLOv3\deep_sort_yolov3-master\yolo3\model.py", line 170, in yolo_eval
    anchors[anchor_mask[l]], num_classes, input_shape, image_shape)
IndexError: index 6 is out of bounds for axis 0 with size 6

I tried my own .h5 Keras model but I had same error. 
Please advise me to use tiny model data and my own Keras model.
Thank you.

**Comment by cvtak** [comment]
I just solve this problem. Thank you.

**Comment by JonathanTW1990** [comment]
> I just solve this problem. Thank you.

Excuse me , How can u fix this problem?

**Comment by dasmehdix** [comment]
> I just solve this problem. Thank you.

Same issue here.How you solved the problem?

**Comment by cvtak** [comment]
Hi there.
I think there is no easy way to use yolov3-tiny.h5 and original h5 because layer information is fixed to YOLOv3. So I modified a lot for model.py and others like as original keras-yolo3.
But I'm not sure my method is right.

**Comment by gyc521zsc** [comment]
@cvtak ,Can you share your model.dy about yolov3-tiny.

**Comment by cvtak** [comment]
Hi, you can already use yolov3-tiny at this pull request. Thank you.
https://github.com/Qidian213/deep_sort_yolov3/pull/128
