### ISSUE TITLE
Poor Result

### ISSUE THREAD

**Issue by takuhara** [Qidian213/deep_sort_yolov3#12]
I gathered people's images and learned with YOLOv3 as one class problem.
(./darknet detector train data/obj.data yolov3.cfg darknet53.conv.74)
The weights of the learning result were better than yolov3.weights in YOLOv3.

Then I converted the weights in convert.py of deep_sort_yolov3 and corrected yolo_anchors.txt and coco_classes.txt appropriately.
However, the tracking success rate of deep_sort_yolov 3 got worse than when using default yolov3.weights(yolo.h5).

Can you think of anything as a cause?

**Comment by Qidian213** [comment]
you can have a show just after yolo detect , check the yolo's performance .

**Comment by takuhara** [comment]
I noticed yolov3 weights can't be converted to keras model.

https://github.com/allanzelener/YAD2K/issues/114
