### ISSUE TITLE
How can use tensorflow-gpu?

### ISSUE THREAD

**Issue by scp-sjrim** [Qidian213/deep_sort_yolov3#14]
Hello

I runned demo.py

but it looked only cpu only.

how can I change it?

thank you +

**Comment by Qidian213** [comment]
have you install cuda and cudnn ?

**Comment by scp-sjrim** [comment]
@Qidian213 Yes I have both.
 cuda 9.0 cudnn7.0 .
I founded the problem.
my tensorflow version was 1.3 so I upgrade 1.8
now it is working ! thanks

**Comment by parvkpr** [comment]
https://github.com/parvkpr/Accident-avoidance-deepsortyoloFCRN
here is an implementation that uses Tensorflow GPU along with deep-sort
