### ISSUE TITLE
Tracking instability

### ISSUE THREAD

**Issue by sxhsunday** [Qidian213/deep_sort_yolov3#15]
hello!
在程序demo.py第76行 
if track.is_confirmed() and tarck.time_since_updata>1
不应该是   if    not    track.is_confirmed() and tarck.time_since_updata>1 吗？
但是我改了之后效果变得很差
请问您有什么解决方法吗

**Comment by Qidian213** [comment]
程序里的就是

2018年6月19日星期二，sxhsunday <notifications@github.com> 写道：
