### ISSUE TITLE
detections

### ISSUE THREAD

**Issue by RandaKhairy** [Qidian213/deep_sort_yolov3#16]
how can we add the object name to the bounding box instead of the track id??

**Comment by Qidian213** [comment]
Do you wants to tracking more than 1 class ?

**Comment by RandaKhairy** [comment]
yes, we want to track 5 objects

**Comment by Qidian213** [comment]
it need process bounding boxes with classes , a lit difficult . i dont want to do it . and i afraid that it may cant track 5 classes
