### ISSUE TITLE
Error while converting

### ISSUE THREAD

**Issue by Choneke** [Qidian213/deep_sort_yolov3#17]
Got the following during training;
Traceback (most recent call last):
    File "convert.py", line 241, in <module>
       _main(parser.parse_args())
     File "convert.py", line 78, in _main
        unique_config_file= unique_config_sections(config_path)
     File "convert.py", line 48, in unique_config_sections
        output_stream.write(line)
TypeError: a bytes-like object is required, not 'str'

![image](https://user-images.githubusercontent.com/39613742/42143864-63eae09e-7df2-11e8-9bdc-e36fcef1b01a.png)

**Comment by sumopal23** [comment]
Hi, I'm getting the same error. How did you fix this? Thanks!

**Comment by 404hasbeenfound** [comment]
Hi, i'm too, would you have some idea to fix it ? I have checked my environment is following:
numpy 1.15.1
sklearn 0.19.2
opencv-python 3.4.3.18 
tensorflow-gpu 1.4.0
keras 2.2.2
Is my environment wrong?
