### ISSUE TITLE
Deep Sort weights for vehicle class?

### ISSUE THREAD

**Issue by prnvjb** [Qidian213/deep_sort_yolov3#18]
Hi everyone,
Thanks for this code. I would like to know whether anybody have deep sort vehicle class weights for vehicle class like cars, trucks etc.?
Please share weights for relevant procedure to train our own set of weights?
Thanks!!

**Comment by Qidian213** [comment]
https://github.com/Qidian213/deep_sort_yolov3/issues/7 

For more you need reference to  https://github.com/nwojke/deep_sort
