### ISSUE TITLE
TinyYolo v3 with maxpool layer conversion?

### ISSUE THREAD

**Issue by karanmartian** [Qidian213/deep_sort_yolov3#19]
Hi I am trying to adapt the convert.py script to convert maxpool layer for supporting TinyYolo v3. How exactly do you go about doing this?

**Comment by karanmartian** [comment]
This is how I have attempted to add the MaxPool Layer support. Is this correct? I am getting a buffer too small error: Traceback (most recent call last):
  File "convert-tiny.py", line 257, in <module>
    _main(parser.parse_args())
  File "convert-tiny.py", line 138, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

-------------------------------------------------------------------------
Code to support Maxpool Layer
-------------------------------------------------------------------------
elif section.startswith('maxpool'):
            size = int(cfg_parser[section]['size'])
            stride = int(cfg_parser[section]['stride'])
            
            padding = 'valid'
            
            # Create MaxPool2D layer
            if stride>1:
                # Darknet uses left and top padding instead of 'same' mode
                prev_layer = ZeroPadding2D(((1,0),(1,0)))(prev_layer)
            maxpool_layer = (MaxPooling2D(
                pool_size=(size,size),
                strides=(stride, stride),
                padding=padding))(prev_layer)
            prev_layer = maxpool_layer

**Comment by karanmartian** [comment]
Ok so I solved that issue by looking at how the layer was implemented in YAD2K and was able to generate the h5 model. Now I am getting this error while running the demo. What is the correct model.py to use for tiny yolo v3?

Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main(YOLO())
  File "/home/karan/deep_sort_yolov3/yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/karan/deep_sort_yolov3/yolo.py", line 72, in generate
    score_threshold=self.score, iou_threshold=self.iou)
  File "/home/karan/deep_sort_yolov3/yolo3/model.py", line 170, in yolo_eval
    anchors[anchor_mask[l]], num_classes, input_shape, image_shape)
IndexError: index 6 is out of bounds for axis 0 with size 6

**Comment by Qidian213** [comment]
I never test yolo-tiny so i am not sure it can be used by this code . for more you can reference to https://github.com/qqwweee/keras-yolo3

**Comment by Anhaoxu** [comment]
Hi, @karanmartian @Qidian213   The problem is solved or not ??? I'm new in keras.这个问题只要把池化层转化成Keras里面的就行了吧

**Comment by Anhaoxu** [comment]
<img width="602" alt="2018-08-01 9 50 58" src="https://user-images.githubusercontent.com/25519842/43496582-aacc6100-9570-11e8-90e3-616afc1296fe.png">
So, in these codes, we only need import keras 2D pooling layer, and transformed it like these code, I see all pooling layers are maxpooling with 2 strides and 2*2 size, so can you add this change? I'll have a try, wish you can add this change. @karanmartian @Qidian213

**Comment by Qidian213** [comment]
sorry , recently was to busy to reply and do it

2018-08-01 9:57 GMT+08:00 Anhaoxu <notifications@github.com>:

**Comment by albertyou2** [comment]
have you solve this problem ? @karanmartian @Qidian213

**Comment by amirzzzz** [comment]
hi. issue solved. 
1- download yolo_v3_tiny.wheight and its config file (yolo_tiny.cfg)
2- download tiny_yolo_anchors.txt from https://github.com/qqwweee/keras-yolo3
3- using yolo_v3_tiny.wheight and  yolo_tiny.cfg  convert.py to convert yolo to .h5 (download it from https://github.com/allanzelener/YAD2K/blob/master/yad2k.py). run yad2k.py
4- now you have yolo_tiny.h5 in model_data folder.
5- go to yolo.py and set: self.model_path = 'model_data/yolo_tiny.h5', self.anchors_path = 'model_data/tiny_yolo_anchors.txt'
6- go to model.py and find anchor_mask, then change it to anchor_mask = [[3,4,5],[0,1,2]]
then go to line168 in model.py (for l in range(3)) and chage it to for l in range(2).
thats it.

**Comment by JonathanTW1990** [comment]
> hi. issue solved.
> 1- download yolo_v3_tiny.wheight and its config file (yolo_tiny.cfg)
> 2- download tiny_yolo_anchors.txt from https://github.com/qqwweee/keras-yolo3

> > 3- using yolo_v3_tiny.wheight and yolo_tiny.cfg convert.py to convert yolo to .h5 (download it from https://github.com/allanzelener/YAD2K/blob/master/yad2k.py). run yad2k.py

**Or you can update convert.py from qqwweee [here](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py) and then get your tiny.h5 for keras command:python3 convert.py yolov3-tiny.cfg yolov3-tiny.weights model_data/yolo_tiny.h5**
> 4- now you have yolo_tiny.h5 in model_data folder.
> 5- go to yolo.py and set: self.model_path = 'model_data/yolo_tiny.h5', self.anchors_path = 'model_data/tiny_yolo_anchors.txt'
> 6- go to model.py and find anchor_mask, then change it to anchor_mask = [[3,4,5],[0,1,2]]
> then go to line168 in model.py (for l in range(3)) and chage it to for l in range(2).
> thats it.

**Comment by liuzaozao7799** [comment]
> 1- download yolo_v3_tiny.wheight and its config file (yolo_tiny.cfg).
> 2- download tiny_yolo_anchors.txt from [qqwweee/keras-yolo3](https://raw.githubusercontent.com/qqwweee/keras-yolo3/master/model_data/tiny_yolo_anchors.txt).
> 3- update convert.py from [qqwweee/keras-yolo3](https://github.com/qqwweee/keras-yolo3/blob/master/convert.py) and then get your tiny.h5 for keras from the command line: 
    `python convert.py yolov3-tiny.cfg yolov3-tiny.weights model_data/yolo_tiny.h5`
> 4- now you have yolo_tiny.h5 in model_data folder.
> 5- go to yolo.py and set: self.model_path = 'model_data/yolo_tiny.h5', self.anchors_path = 'model_data/tiny_yolo_anchors.txt'.
> 6- (make some changes.👇)
> 7- (make some changes.👇)

**Great! It works!** And I changed some codes for more flexibility, it also refers to [qqwweee/keras-yolo3](https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo3/model.py#L364):

**6**- go to model.py and ctrl + F, find 3 _**anchor_mask**_ in yolo_eval()、preprocess_true_boxes() and yolo_loss(), then change _**anchor_mask = [[6,7,8], [3,4,5], [0,1,2]]**_ to **_anchor_mask = [[3,4,5],[0,1,2]]_** by condition 👇:

- [ ] In yolo_eval():

```
num_layers = len(yolo_outputs) # default setting
anchor_mask = [[6,7,8], [3,4,5], [0,1,2]] if num_layers == 3 else [[3, 4, 5], [0, 1, 2]]  # considering tiny_yolo
```

- [ ] In preprocess_true_boxes():

```
num_layers = len(anchors) // 3  # default setting
anchor_mask = [[6, 7, 8], [3, 4, 5], [0, 1, 2]] if num_layers == 3 else [[3, 4, 5], [0, 1, 2]]  # considering tiny_yolo
```

- [ ] In yolo_loss():

```
num_layers = len(yolo_outputs)  # default setting
anchor_mask = [[6,7,8], [3,4,5], [0,1,2]] if num_layers == 3 else [[3, 4, 5], [0, 1, 2]]  # considering tiny_yolo
```
**And also**
**7**- still in model.py and ctrl + F, find all the **_range(3)_** and chage them all to **_range(num_layers)_**:

- [ ] There are a total of 6 **_range(3)_**: 1 in yolo_eval()、3 in preprocess_true_boxes() and 2 in yolo_loss().

**Comment by MuhammadAsadJaved** [comment]
@liuzaozao7799  Very good work.
