### ISSUE TITLE
How to use Custom Trained Yolo v3 model

### ISSUE THREAD

**Issue by sushant1727** [Qidian213/deep_sort_yolov3#23]
Hello, first of all, thank you for your hard work.

I've trained Yolo v3 model for the custom object(person, logo on the shirt) detection. After I convert it to h5 file. and run demo.py it throws error.

> File "/home/deep_sort_yolov3/yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/home/deep_sort_yolov3/yolo.py", line 72, in generate
    score_threshold=self.score, iou_threshold=self.iou)
  File "/home/deep_sort_yolov3/yolo3/model.py", line 170, in yolo_eval
    anchors[anchor_mask[l]], num_classes, input_shape, image_shape)
IndexError: index 6 is out of bounds for axis 0 with size 6
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f36234d45f8>>
Traceback (most recent call last):
  File "/home/.virtualenvs//lib/python3.5/site-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable

After going through issues I see yolo.py is using coc_classes.txt and yolo_anchors.txt files. I manually edited the coco_classes.txt and added the name of custom object(person, logo) I'm looking to detect.

I am stuck at yolo_anchors.txt and voc_classes.txt file how can I edit them to get the detection +tracking.

**Comment by sushant1727** [comment]
I got the solution for yolo_anchors.txt using this since I used the Alexey repo to train my custom model 'https://github.com/AlexeyAB/darknet/blob/master/scripts/gen_anchors.py'

**Comment by AngelababyTing** [comment]
hello, @sushant1727 
How do you transfer your training data .weight to .h5 module?
Do you use your own training data .weight not yolov3.weight?

**Comment by sushant1727** [comment]
@AngelababyTing  I trained my own custom model in Yolo and converted it to h5 using one of the conversion tools.[ See this link for reference.](https://github.com/qqwweee/keras-yolo3)

**Comment by songjunqianli** [comment]
hello，@AngelababyTing  
you can use 'convert.py' to transfer your training data .weight to .h5
