### ISSUE TITLE
Tracking on 1fps Camera

### ISSUE THREAD

**Issue by MartyEz** [Qidian213/deep_sort_yolov3#25]
Hi,

Thanks a lot for your work, very helpful. It's work great on some videos. I am working on 1fps camera and its doesn't work well, as expected. Persons create a new id at each footstep. I think it's due to the very low fps, person look like teleporting. Maybe the velocity model of the kalman filter sould be changed.
Do you know how can i manage this by modifying some value ?
What the mean of nms_max_overlap and nn_budget ?

Thanks

**Comment by sakares** [comment]
After I have played around the repository, the rapidly changed position problem regarding low fps or non-constant speed could be compensated by increasing the uncertainty value on Kalman filter by changing line of code here inside here: https://github.com/nwojke/deep_sort/blob/master/deep_sort/kalman_filter.py#L52

default:
`self._std_weight_position = 1. / 20`

I have changed to somewhat around 
`self._std_weight_position = 1. / 5`

and it seems work but not permanent solution. You need to figure out which value is right for your setting. Hope it helps.
