### ISSUE TITLE
How can I measure the accuracy of this deep sort on my own video?

### ISSUE THREAD

**Issue by Akhtar303nu** [Qidian213/deep_sort_yolov3#36]
I want to check the performance of this deep sort?
How can I can do that
Thanks

**Comment by Akhtar303nu** [comment]
@404hasbeenfound  go to demo.py and give the path of your video
like this
cap = cv2.VideoCapture('/home/akhtar/Desktop/vehicle17.mp4')

**Comment by 404hasbeenfound** [comment]
I just change the code like this.
![change code](https://user-images.githubusercontent.com/37691681/46597492-d351bf80-cb12-11e8-9df1-c04a8a934e81.png)
but i continue run this code with 'python demo.py', then there is a video called output.avi, but the output.avi is 0 Bytes, so it failed, could you help me?

**Comment by 404hasbeenfound** [comment]
@Akhtar303nu I got it, thanks a lot!

**Comment by 404hasbeenfound** [comment]
@Akhtar303nu  I happened that i can detect and track only one video, but cannot track the other video, have you happened to this? you can track your second video to confirm it. May you happy.Thanks a lot.

**Comment by Akhtar303nu** [comment]
@404hasbeenfound at a time you can use only one video but it work for any video (.mp4) extension
I tested in alot of videos

**Comment by 404hasbeenfound** [comment]
@Akhtar303nu   I have figured it out. Thanks a lot!

**Comment by Qidian213** [comment]
For test MOTA need benachmark , there may no way to test MOTA on your own videos.
