### ISSUE TITLE
Tracking on PTZ camera

### ISSUE THREAD

**Issue by htadashi** [Qidian213/deep_sort_yolov3#37]
First of all,  thanks for sharing this project! :)

I tried to run the tracker on a PTZ Optics camera by changing the following line of _demo.py_:

> video_capture = cv2.VideoCapture(0)

to 

> video_capture = cv2.VideoCapture('rtsp://[_IP_]/1')

where [_IP_] is the IP address of the camera.  When I run _demo.py_ the capture window opens, but freezes on the first frame. What could be the problem?

Thanks and best regards!

**Comment by htadashi** [comment]
Solved the problem. I was running demo.py without using tensorflow-gpu, so the fps rate was very slow.

**Comment by vimukthimudalige** [comment]
Did you implement the ptz camera moving part with the tracked person?

**Comment by vimukthimudalige** [comment]
How did you make this use full gpu?

**Comment by htadashi** [comment]
> Did you implement the ptz camera moving part with the tracked person?

I am still implementing. To control the ptz camera I'm using this code: https://github.com/beerobber/pycambot/blob/master/CameraController.py

> How did you make this use full gpu?

Just installed the python package tensorflow-gpu instead of tensorflow. I'm using CUDA v9.0.176.
