### ISSUE TITLE
How to limit only to track one human or get a count on active number of tracking?

### ISSUE THREAD

**Issue by vimukthimudalige** [Qidian213/deep_sort_yolov3#42]

**Comment by sumopal23** [comment]
Did you get it to get a count on the number of people?

**Comment by vimukthimudalige** [comment]
no i have not yet being able to get a count to find the active number of people.

**Comment by Qidian213** [comment]
For the unstable IDs i afraid it is difficult to count really person number , it needs to improve . For track one person you can reference to VOT challenge.
