### ISSUE TITLE
sklean问题

### ISSUE THREAD

**Issue by AIrobot6** [Qidian213/deep_sort_yolov3#46]
怎么安装sklean？？？

**Comment by 404hasbeenfound** [comment]
may be baidu.com can help you.

**Comment by AIrobot6** [comment]
> 可能baidu.com可以帮到你。

你好， 我是在百度上找过之后 没有解决 才来这里的，您能给我帮助么?

**Comment by AIrobot6** [comment]
> > 可能baidu.com可以帮到你。
> 
> 你好，我是在百度上找过之后没有解决才来这里的，你能给我帮

> 可能baidu.com可以帮到你。

请问 sklean 还是sklearn??

**Comment by AIrobot6** [comment]
> 但我安装了以下软件，代码也无法运行。

你的报错 和我一样么？

**Comment by louxy126** [comment]
我直接pip install sklearn 是可以运行的，另外，请问你有没有试过换自己的模型跟踪目标？
