### ISSUE TITLE
跟踪自己的目标

### ISSUE THREAD

**Issue by louxy126** [Qidian213/deep_sort_yolov3#56]

**Comment by louxy126** [comment]
博主你好、感谢你提供的代码！
我现在想用它实现车辆跟踪、我曾经用https://github.com/qqwweee/keras-yolo3训练过一个车辆检测的模型、请问是不是只要将你的代码中的yolo.py中的model-path改为我训练的结果、anchor—path和classes-path改为我训练时所用的文件路径就可以了？另外、我看b站的视频里面行人的id有个位数的也有大几十的、请问这是因为代码存在瑕疵吗？十分感谢

**Comment by louxy126** [comment]
我试着用上面的方法，将yolo.py改为下面
`self.model_path = '~/PycharmProjects/keras-yolo3-master/logs/000/trained_weights.h5'
        self.anchors_path = '~/PycharmProjects/keras-yolo3-master/model_data/yolo_anchors.txt'
        self.classes_path = '~/PycharmProjects/keras-yolo3-master/model_data/voc_classes.txt'`

其中 trained_weights.h5 是我使用 yolo_anchors.txt'和voc_classes.txt'`在https://github.com/qqwweee/keras-yolo3   中训练出的结果，只有车、人两类目标。
但是报错
`Traceback (most recent call last):
  File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/demo.py", line 112, in <module>
    main(YOLO())
  File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/yolo.py", line 33, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/yolo.py", line 54, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "/home/jsu/anaconda3/envs/deep_sort/lib/python3.5/site-packages/keras/models.py", line 241, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
`
请问你知道该怎么解决吗？（我用https://github.com/qqwweee/keras-yolo3 中原始的yolo.h5是可以成功检测和跟踪的）

**Comment by irisqp** [comment]
> 
> 
> 这个问题可能需要你自己来解决，另外是 yolo.py 文件 line 100 `if predicted_class != 'person' :` 需要修改一下。 因为deep sort 是用的行人重识别数据集训练的，更专注于提取人体特征，在车辆跟踪可能效果不好，你可以尝试自己用车的数据集训练一下deep sort的模型。 [https://github.com/nwojke/cosine_metric_learning](url)
感谢楼主的工作，我也想做车辆跟踪，请问怎么训练deep sort呢？我点开你给的这个链接，是空的。

**Comment by Qidian213** [comment]
https://github.com/nwojke/cosine_metric_learning

**Comment by Desire-zone** [comment]
> 我试着用上面的方法，将yolo.py改为下面
> `self.model_path = '~/PycharmProjects/keras-yolo3-master/logs/000/trained_weights.h5' self.anchors_path = '~/PycharmProjects/keras-yolo3-master/model_data/yolo_anchors.txt' self.classes_path = '~/PycharmProjects/keras-yolo3-master/model_data/voc_classes.txt'`
> 
> 其中 trained_weights.h5 是我使用 yolo_anchors.txt'和voc_classes.txt'`在https://github.com/qqwweee/keras-yolo3 中训练出的结果，只有车、人两类目标。 但是报错 `Traceback (most recent call last):
> File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/demo.py", line 112, in
> main(YOLO())
> File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/yolo.py", line 33, in **init**
> self.boxes, self.scores, self.classes = self.generate()
> File "/media/jsu/205E470B5E46D8E4/lxy/deep_sort_yolov3/yolo.py", line 54, in generate
> self.yolo_model = load_model(model_path, compile=False)
> File "/home/jsu/anaconda3/envs/deep_sort/lib/python3.5/site-packages/keras/models.py", line 241, in load_model
> raise ValueError('No model found in config file.')
> ValueError: No model found in config file.
> `
> 请问你知道该怎么解决吗？（我用https://github.com/qqwweee/keras-yolo3 中原始的yolo.h5是可以成功检测和跟踪的）

遇到同样的问题，我请问你解决了吗
