### ISSUE TITLE
Why change if not track.is_confirmed() or track.time_since_update > 1 ？

### ISSUE THREAD

**Issue by fdy200533** [Qidian213/deep_sort_yolov3#59]
Thanks a lot for your work～
But I found a difference between the code by nwojke and yours，while in line 76 in your demo.py is 
`if track.is_confirmed() and track.time_since_update >1 :`
and in the deep_sort_app.py by nwojke is 
`if not track.is_confirmed() or track.time_since_update > 1:`
Why change this? Or it is a mistake in origin code? Perform worse or better?

**Comment by Qidian213** [comment]
Sorry for the bug ，I had already fixed it on my code ,but forgot to update github . it should be `if not track.is_confirmed() or track.time_since_update > 1:`

**Comment by fdy200533** [comment]
> Sorry for the bug ，I had already fixed it on my code ,but forgot to update github . it should be `if not track.is_confirmed() or track.time_since_update > 1:`

All right...
