### ISSUE TITLE
features = encoder(frame,boxs) line very slow

### ISSUE THREAD

**Issue by fangmingbnu** [Qidian213/deep_sort_yolov3#6]
hi, @Qidian213 .

I am using your code to do the tracking with tin-yolo model. Current I could get around 3-4 fps on cpu. I want to improve that. However, I found that the line 60 in demo.py which is "features = encoder(frame,boxs)" take 100 ms for 1 image, which waste a lot of time. I want to ask whether there has a way to improve this? Thank you!

**Comment by Qidian213** [comment]
This question you should ask the author of deep_sort . Actually , it is very fast if it only took 100 ms per frame on cpu. If you use a video that contains fewer people per frame it can faster .～ ^_^ ～
