### ISSUE TITLE
How would you change tracking from people to cars?

### ISSUE THREAD

**Issue by cesarandreslopez** [Qidian213/deep_sort_yolov3#7]
First of all great job! This was most useful.

Any pointers on how to change this tracker from people to cars?

**Comment by anshu1106** [comment]
Change the part in the yolo detector code where we filter 'person' from detected boxes.
In yolo.py 

 for i, c in reversed(list(enumerate(out_classes))):
            predicted_class = self.class_names[c]
            if predicted_class != 'person' :
                continue
            box = out_boxes[i]
Change 'person' to 'car'.

**Comment by cesarandreslopez** [comment]
Excellent! Missed that, thank you for the pointer! @anshu1106

**Comment by Qidian213** [comment]
Maybe not , the deep_sort model was just trained for person

**Comment by cesarandreslopez** [comment]
I can confirm that it tracks cars, birds and trucks too and performs well.

**Comment by Qidian213** [comment]
Maybe deep_sort more like a feature coding and similarity comparator ,  no matter what object it is  .

**Comment by Megaclick** [comment]
hi!, there's a way to track multiple objects?, like cars and trucks at the same time?

**Comment by Qidian213** [comment]
you can have a try . they all belong to "car" , just like @anshu1106  say  to have a try .

**Comment by zooezou** [comment]
Thanks a lot ,btw it can be easily used to track cars. It's favoured if the relevant paper can be provide  : )

**Comment by Goldwh** [comment]
I want to track other things, not people, cars, birds, etc. However, the tracking effect is not good. How should I train again?

**Comment by Qidian213** [comment]
@Goldwh  You can reference to https://github.com/nwojke/deep_sort

**Comment by sherlockchou86** [comment]
yolo is used for detection, which can detect 80 classes with coco dataset.
deep_sort can only calculate person appearance features with default model. even though you detect multi targets such as cars, truck, bird etc with yolo, the deep_sort tracking performace would not be well.

you need train your own model for tracking.

**Comment by lifeofzi** [comment]
> hi!, there's a way to track multiple objects?, like cars and trucks at the same time?

yes.

Change the part in the yolo detector code where we filter 'person' from detected boxes.
In yolo.py

for i, c in reversed(list(enumerate(out_classes))):
predicted_class = self.class_names[c]
if predicted_class != 'car' and predicted_class!='truck' :
continue
box = out_boxes[i]
Change 'person' to 'car'.

**Comment by vaibhawvipul** [comment]
> yolo is used for detection, which can detect 80 classes with coco dataset.
> deep_sort can only calculate person appearance features with default model. even though you detect multi targets such as cars, truck, bird etc with yolo, the deep_sort tracking performace would not be well.
> 
> you need train your own model for tracking.

I agree. DeepSort is trained for Person Re-Identification. I wanted to track people and cars together, I observed a lot of ID switches for vehicles. so, If you want to use the same model to track multiple objects then it would need to be trained again.
