### ISSUE TITLE
`convert.py` TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by JackDeSomeTrades** [Qidian213/deep_sort_yolov3#8]
Hi,
I'm unable to convert the Darknet model to a Keras model. I'm getting the following error:

`Using TensorFlow backend.`
`Loading weights.`
`Weights Header:  0 2 0 [32013312]`
`Parsing Darknet config.`
`Traceback (most recent call last):`
  `File "convert.py", line 241, in <module>`
    `_main(parser.parse_args())`
  `File "convert.py", line 78, in _main`
    `unique_config_file = unique_config_sections(config_path)`
  `File "convert.py", line 48, in unique_config_sections`
    `output_stream.write(line)`
`TypeError: a bytes-like object is required, not 'str'`

Any idea on how to solve this? Thanks.

**Comment by Qidian213** [comment]
https://github.com/Qidian213/deep_sort_yolov3/issues/3
