### ISSUE TITLE
Tracks in text

### ISSUE THREAD

**Issue by Ntweat** [Qidian213/deep_sort_yolov3#9]
Hi again

Is there are way to get the tracks in a text file.

**Comment by Qidian213** [comment]
Use video with bounding boxes text file ? just like the text file i save in code ? it is easy , you only need to delete yolo detect function and read bounding boxes from text file .  If you want to save the last tracking , i have not studied it yet

**Comment by Ntweat** [comment]
Ok

I want like this. 

Person 1 
Frame 1 location X Y
Frame 2 location XY 




Person N 
Frame    location X Y

**Comment by Qidian213** [comment]
You can do it by yourself by use tracking ID .
