### ISSUE TITLE
Some points to use own data & darknet converted weights

### ISSUE THREAD

**Issue by kazuya-n** [Qidian213/deep_sort_yolov3#90]
It's no longer issue,  but we have to be careful with these points. To detect original dataset & use original trained darknet weights.

- [ ] `convert.py` works well on **Python 2**
- [ ] Specify collect size of trained (detected) image. https://github.com/Qidian213/deep_sort_yolov3/blob/c0a82cab0d0777432a9f1cd43ef0ba0d703f836d/yolo.py#L31
- [ ] Be careful that original code ignores everything but person. (We can simply delete these lines to detect all classes, but SORT algorithm is aimed to detect person.)
https://github.com/Qidian213/deep_sort_yolov3/blob/c0a82cab0d0777432a9f1cd43ef0ba0d703f836d/yolo.py#L100-L101
- [ ] We can detect our own video data by changing this line like `cv2.VideoCapture("detect.avi")`
https://github.com/Qidian213/deep_sort_yolov3/blob/c0a82cab0d0777432a9f1cd43ef0ba0d703f836d/demo.py#L39
- [ ] Origninal darknet yolov3's colorspace is `RGB`, **but opencv's one is `BGR`**, We must convert colorspaces to use trained data by darknet.
https://github.com/Qidian213/deep_sort_yolov3/blob/c0a82cab0d0777432a9f1cd43ef0ba0d703f836d/demo.py#L57
    - We can convert colorspaces by changing this line like `image = Image.fromarray(frame[:,:,::-1])`

**Comment by Qidian213** [comment]
Thanks
