### ISSUE TITLE
How do I track more than one class?

### ISSUE THREAD

**Issue by luiscosio** [Qidian213/deep_sort_yolov3#96]
Hello!

How can I use this to track more than one class at the same time? (Ex. Persons and cars)

Regards!

**Comment by kazuya-n** [comment]
just remove this line
https://github.com/Qidian213/deep_sort_yolov3/blob/fbc993948e9d61b2e1e0367ab0edf3e7d08022fd/yolo.py#L100

but deep sort pre-trained model `mars-small128.pb` is trained to track only person

**Comment by luiscosio** [comment]
Thank you @kazuya-n, any idea how can I use different color bounding boxes for each class is tracking and different counters for each class?

So for example, I can track cars and pedestrians, each one of those categories with different colors and different counts.

**Comment by PassantReyad** [comment]
But if we remove line 100 the code will track any class of the network class_names. Any ideas on how to force the code to just track two or three classes at the same time?

**Comment by PassantReyad** [comment]
I can say the code can track cars!! but how can we track two classes at the same time! 
my trial: if predicted_class != 'person' or 'car' :  did not work !! I also did( if predicted_class != 'person':)(elif predicted_class != 'car':) also did not work!!
Any ideas??

**Comment by luiscosio** [comment]
@PassantReyad To track persons and cars you need to edit line 101 for this:

```
if predicted_class != 'person' and predicted_class != 'car':
                continue
```

**Comment by liujs1016** [comment]
Did you solve it?
Can you tell me how to solve it?
